{
    'name': "EBERE addon",
    'summary': 'This module adds additional documents for external reports and manipulates email templates',
    'author': 'MINcom Smart Solutions GmbH',
    'category': 'Base',
    'version': '17.0.1.5',
    'depends': [
        'l10n_din5008',
        'mail',
        'web',
        'auth_signup',
        'account',
        'base',
        'product',
    ],
    'data': [
        'data/products.xml',
        'views/report_templates.xml',
        'views/invoice_template.xml',
        'data/report_layout.xml',
    ],
    'installable': True,
    'auto_install': True,
    'application': False,
}
